// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: amp/dataplane/v1/dataplane.proto

package dataplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlane_Handshake_FullMethodName     = "/amp.dataplane.v1.DataPlane/Handshake"
	DataPlane_Transfer_FullMethodName      = "/amp.dataplane.v1.DataPlane/Transfer"
	DataPlane_Result_FullMethodName        = "/amp.dataplane.v1.DataPlane/Result"
	DataPlane_StreamingTask_FullMethodName = "/amp.dataplane.v1.DataPlane/StreamingTask"
)

// DataPlaneClient is the client API for DataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataPlane — troca segura de dados entre consumer e provider (P2P).
// MVP: Handshake + Transfer/Result sobre TLS; E2E encryption em fase posterior.
type DataPlaneClient interface {
	// Handshake — troca de chaves efêmeras (ou no MVP apenas validação de session_token).
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Transfer — envio de payload (cifrado em E2E ou em claro sobre TLS no MVP).
	Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedChunk, TransferAck], error)
	// Result — recebimento de resultado.
	Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedChunk], error)
	// Streaming bidirecional para tasks longas (opcional no MVP).
	StreamingTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncryptedChunk, EncryptedChunk], error)
}

type dataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneClient(cc grpc.ClientConnInterface) DataPlaneClient {
	return &dataPlaneClient{cc}
}

func (c *dataPlaneClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, DataPlane_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedChunk, TransferAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[0], DataPlane_Transfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncryptedChunk, TransferAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_TransferClient = grpc.ClientStreamingClient[EncryptedChunk, TransferAck]

func (c *dataPlaneClient) Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[1], DataPlane_Result_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResultRequest, EncryptedChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_ResultClient = grpc.ServerStreamingClient[EncryptedChunk]

func (c *dataPlaneClient) StreamingTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncryptedChunk, EncryptedChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[2], DataPlane_StreamingTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncryptedChunk, EncryptedChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamingTaskClient = grpc.BidiStreamingClient[EncryptedChunk, EncryptedChunk]

// DataPlaneServer is the server API for DataPlane service.
// All implementations must embed UnimplementedDataPlaneServer
// for forward compatibility.
//
// DataPlane — troca segura de dados entre consumer e provider (P2P).
// MVP: Handshake + Transfer/Result sobre TLS; E2E encryption em fase posterior.
type DataPlaneServer interface {
	// Handshake — troca de chaves efêmeras (ou no MVP apenas validação de session_token).
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Transfer — envio de payload (cifrado em E2E ou em claro sobre TLS no MVP).
	Transfer(grpc.ClientStreamingServer[EncryptedChunk, TransferAck]) error
	// Result — recebimento de resultado.
	Result(*ResultRequest, grpc.ServerStreamingServer[EncryptedChunk]) error
	// Streaming bidirecional para tasks longas (opcional no MVP).
	StreamingTask(grpc.BidiStreamingServer[EncryptedChunk, EncryptedChunk]) error
	mustEmbedUnimplementedDataPlaneServer()
}

// UnimplementedDataPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneServer struct{}

func (UnimplementedDataPlaneServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedDataPlaneServer) Transfer(grpc.ClientStreamingServer[EncryptedChunk, TransferAck]) error {
	return status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedDataPlaneServer) Result(*ResultRequest, grpc.ServerStreamingServer[EncryptedChunk]) error {
	return status.Error(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedDataPlaneServer) StreamingTask(grpc.BidiStreamingServer[EncryptedChunk, EncryptedChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamingTask not implemented")
}
func (UnimplementedDataPlaneServer) mustEmbedUnimplementedDataPlaneServer() {}
func (UnimplementedDataPlaneServer) testEmbeddedByValue()                   {}

// UnsafeDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServer will
// result in compilation errors.
type UnsafeDataPlaneServer interface {
	mustEmbedUnimplementedDataPlaneServer()
}

func RegisterDataPlaneServer(s grpc.ServiceRegistrar, srv DataPlaneServer) {
	// If the following call panics, it indicates UnimplementedDataPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlane_ServiceDesc, srv)
}

func _DataPlane_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServer).Transfer(&grpc.GenericServerStream[EncryptedChunk, TransferAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_TransferServer = grpc.ClientStreamingServer[EncryptedChunk, TransferAck]

func _DataPlane_Result_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneServer).Result(m, &grpc.GenericServerStream[ResultRequest, EncryptedChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_ResultServer = grpc.ServerStreamingServer[EncryptedChunk]

func _DataPlane_StreamingTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServer).StreamingTask(&grpc.GenericServerStream[EncryptedChunk, EncryptedChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamingTaskServer = grpc.BidiStreamingServer[EncryptedChunk, EncryptedChunk]

// DataPlane_ServiceDesc is the grpc.ServiceDesc for DataPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amp.dataplane.v1.DataPlane",
	HandlerType: (*DataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _DataPlane_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _DataPlane_Transfer_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Result",
			Handler:       _DataPlane_Result_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamingTask",
			Handler:       _DataPlane_StreamingTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "amp/dataplane/v1/dataplane.proto",
}
